sudo: false
language: node_js
node_js:
  - 4.15.4 # use nodejs v4.15.4
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - npx hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
